package http

import (
	"encoding/json"
	"net/http"
	"reflect"
	"testing"
)

// publishedCatalogJSON is copied verbatim from docs/API_EXAMPLES.md, which is itself
// generated by marshalling the real response structures (ADR-0016). Comparing decoded
// values rather than bytes keeps the test about the contract and not about whitespace.
const publishedCatalogJSON = `{
  "operations": [
    {
      "id": "add",
      "name": "Addition",
      "symbol": "+",
      "arity": 2,
      "parameters": [
        { "name": "augend", "description": "The value added to." },
        { "name": "addend", "description": "The value added." }
      ],
      "endpoint": "/api/v1/operations/add"
    },
    {
      "id": "subtract",
      "name": "Subtraction",
      "symbol": "−",
      "arity": 2,
      "parameters": [
        { "name": "minuend", "description": "The value subtracted from." },
        { "name": "subtrahend", "description": "The value subtracted." }
      ],
      "endpoint": "/api/v1/operations/subtract"
    },
    {
      "id": "multiply",
      "name": "Multiplication",
      "symbol": "×",
      "arity": 2,
      "parameters": [
        { "name": "multiplicand", "description": "The value multiplied." },
        { "name": "multiplier", "description": "The number of times it is taken." }
      ],
      "endpoint": "/api/v1/operations/multiply"
    },
    {
      "id": "divide",
      "name": "Division",
      "symbol": "÷",
      "arity": 2,
      "parameters": [
        { "name": "dividend", "description": "The value divided." },
        { "name": "divisor", "description": "The value divided by. Must not be zero." }
      ],
      "endpoint": "/api/v1/operations/divide"
    },
    {
      "id": "power",
      "name": "Exponentiation",
      "symbol": "^",
      "arity": 2,
      "parameters": [
        { "name": "base", "description": "The value raised to a power." },
        { "name": "exponent", "description": "The power the base is raised to." }
      ],
      "endpoint": "/api/v1/operations/power"
    },
    {
      "id": "sqrt",
      "name": "Square root",
      "symbol": "√",
      "arity": 1,
      "parameters": [
        { "name": "radicand", "description": "The value whose square root is taken. Must not be negative." }
      ],
      "endpoint": "/api/v1/operations/sqrt"
    },
    {
      "id": "percent",
      "name": "Percentage",
      "symbol": "%",
      "arity": 2,
      "parameters": [
        { "name": "percentage", "description": "The percentage to take." },
        { "name": "value", "description": "The value the percentage is taken of." }
      ],
      "endpoint": "/api/v1/operations/percent"
    }
  ]
}`

func TestCatalogMatchesThePublishedDocument(t *testing.T) {
	server := newServer(t, Config{})

	got := get(t, server, "/api/v1/operations")
	if got.status != http.StatusOK {
		t.Fatalf("status = %d, want 200\nbody: %s", got.status, got.body)
	}

	var served, published any
	got.decode(t, &served)
	if err := json.Unmarshal([]byte(publishedCatalogJSON), &published); err != nil {
		t.Fatalf("the published catalog in this test is not valid JSON: %v", err)
	}

	if !reflect.DeepEqual(served, published) {
		t.Errorf("catalog does not match docs/API_EXAMPLES.md\n served: %s\n", got.body)
	}
}

// The response carries exactly the documented fields, no more: the schema declares
// additionalProperties false, and an extra field is a contract break even if nothing reads
// it yet.
func TestCatalogCarriesNoUndocumentedFields(t *testing.T) {
	server := newServer(t, Config{})

	var envelope map[string]json.RawMessage
	got := get(t, server, "/api/v1/operations")
	got.decode(t, &envelope)

	if len(envelope) != 1 {
		t.Errorf("catalog envelope has fields %v, want only operations", keysOf(envelope))
	}

	var operations []map[string]json.RawMessage
	if err := json.Unmarshal(envelope["operations"], &operations); err != nil {
		t.Fatalf("decoding operations: %v", err)
	}

	wantFields := []string{"id", "name", "symbol", "arity", "parameters", "endpoint"}
	for _, operation := range operations {
		if len(operation) != len(wantFields) {
			t.Errorf("operation has fields %v, want %v", keysOf(operation), wantFields)
		}
		for _, field := range wantFields {
			if _, ok := operation[field]; !ok {
				t.Errorf("operation %v is missing %q", keysOf(operation), field)
			}
		}
	}
}

func keysOf[V any](m map[string]V) []string {
	names := make([]string, 0, len(m))
	for name := range m {
		names = append(names, name)
	}
	return names
}
